// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc488.OnRobotCode.subsystems;
import org.usfirst.frc488.OnRobotCode.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Sensors extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder leftFollowWheel = RobotMap.sensorsLeftFollowWheel;
    Encoder rightFollowWheel = RobotMap.sensorsRightFollowWheel;
    Encoder middleFollowWheel = RobotMap.sensorsMiddleFollowWheel;
    AnalogChannel frontCollectorPot = RobotMap.sensorsFrontCollectorPot;
    AnalogChannel backCollectorPot = RobotMap.sensorsBackCollectorPot;
    AnalogChannel frontCollectorBallDetector = RobotMap.sensorsFrontCollectorBallDetector;
    AnalogChannel backCollectorBallDetector = RobotMap.sensorsBackCollectorBallDetector;
    AnalogChannel ballSettledInCatapult = RobotMap.sensorsBallSettledInCatapult;
    AnalogChannel catapultPotentiometer = RobotMap.sensorsCatapultPotentiometer;
    DigitalInput frontUpLimitSwitch = RobotMap.sensorsFrontUpLimitSwitch;
    DigitalInput frontDownLimitSwitch = RobotMap.sensorsFrontDownLimitSwitch;
    DigitalInput backUpLimitSwitch = RobotMap.sensorsBackUpLimitSwitch;
    DigitalInput backDownLimitSwitch = RobotMap.sensorsBackDownLimitSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
