// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc488.ActualRobot.subsystems;
import org.usfirst.frc488.ActualRobot.RobotMap;
import org.usfirst.frc488.ActualRobot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Actuators extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Compressor compressor = RobotMap.actuatorsCompressor;
    Solenoid bucketSolenoid = RobotMap.actuatorsBucketSolenoid;
    SpeedController leftFrontController = RobotMap.actuatorsLeftFrontController;
    SpeedController leftRearController = RobotMap.actuatorsLeftRearController;
    SpeedController rightFrontController = RobotMap.actuatorsRightFrontController;
    SpeedController rightRearController = RobotMap.actuatorsRightRearController;
    Solenoid fingerSolenoid = RobotMap.actuatorsFingerSolenoid;
    SpeedController collectorSpeedController = RobotMap.actuatorsCollectorSpeedController;
    SpeedController innerShooterSpeedController = RobotMap.actuatorsInnerShooterSpeedController;
    SpeedController outerShooterSpeedController = RobotMap.actuatorsOuterShooterSpeedController;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
